redis:
    image: redis
    ports:
        - "6379:6379"
elasticsearch:
    image: elasticsearch
    ports:
        - "9200:9200"
        - "9300:9300"
logstash:
    build: logstash/
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
    ports:
      - "5000:5000"
    links:
      - redis
      - elasticsearch
kibana:
    image: kibana
    ports:
        - "5601:5601"
    links:
        - elasticsearch
